### ISSUE TITLE
No documentation on how to access Grafana.

### ISSUE THREAD

**Issue by tonycosentini** [dokku/dokku-graphite-grafana#1]
Apologies if this is a dumb question - but I can't see any instructions on how to access the Grafana frontend once this is installed.

It looks like there is a way to expose statsd ports externally, but I don't see anything about Grafana.

Apologies if I'm missing something, thanks!

**Comment by trinode** [comment]
I'm not sure it's a documentation issue, it looks like you can't without ssh port forwarding, maybe I'm wrong though?

**Comment by josegonzalez** [comment]
Sorry about that, was a simple change, just finally got around to giving the datastore plugins some love :)
