### ISSUE TITLE
Why is this a plugin?

### ISSUE THREAD

**Issue by dmr** [dokku/dokku-graphite-grafana#11]
Maybe this is a stupid question but anyway:

IMO there could be a dokku-graphite with a Dockerfile and installation instructions.

dokku plugins are nice but I'd rather have something that is just an app to try it out because I don't want to risk breaking my production system with a plugin.

Do you have an opinion about this, dokku-graphite-grafana maintainers?

**Comment by josegonzalez** [comment]
If you want to deploy graphite on your own, you are welcome to do so, and nothing is preventing you from setting up such an app.

This is a plugin because it is a plugin.
