### ISSUE TITLE
"Permission denied" when trying to create a link to an app

### ISSUE THREAD

**Issue by elkdanger** [dokku/dokku-graphite-grafana#8]
I'm getting this error when trying to link my app to the Graphite plugin:

```
$ dokku graphite:link default tt2-service
/var/lib/dokku/plugins/available/docker-options/functions: line 82: /home/dokku/tt2-service/DOCKER_OPTIONS_DEPLOY: Permission denied
```

I've also tried with `sudo` but to no avail. I've checked the DOCKER_OPTIONS_BUILD file inside the app and it has the link declaration in there. Is this something I should be worried about?

**Comment by NonoMDM** [comment]
I had same issue, when my plugin wasn't in correct folder. Try to delete plugin and install it directly in <app> plugin folder

**Comment by josegonzalez** [comment]
Sounds like you changed the permissions on that file, which should be owned by `dokku:dokku`. Change it back via `chown` and you should be fine.
