### ISSUE TITLE
How do I access Graphite data from Grafana?

### ISSUE THREAD

**Issue by elkdanger** [dokku/dokku-graphite-grafana#9]
I've got the Grafana front-end set up using the Dokku plugin but I can't seem to access the Graphite data. Is it possible to expose the Graphite front-end?

As far as I'm aware, we need that so we can add in the Graphite data source into Grafana.

**Comment by elkdanger** [comment]
Never mind, I read the documentation!

FYI: set your datasource up to point to http://localhost:8000

**Comment by darklow** [comment]
```
dokku graphite:nginx-expose <service> <domain>
```
